ToDoApp/ToDoApp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^todo/', include('todo.urls')),
]

ToDoApp/todo/urls.py
"""
   Copyright 2016 Andrea McIntosh

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 """

from django.conf.urls import url, include
from . import views

app_name = 'todo'
urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.list_details, name='detail'),
    url(r'^(?P<pk>[0-9]+)/newitem/$', views.new_item, name='new_item'),
    url(r'^newlist/$', views.new_list, name='new_list'),
    url(r'^register/$', views.register, name='register'),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^accounts/logout/$', views.user_logout, name='logout'),
    url(r'^accounts/viewlists/$', views.view_lists, name='viewlists'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

ToDoApp/todo/models.py
"""
   Copyright 2016 Andrea McIntosh

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 """

import datetime
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models

class TodoList(models.Model):
    list_title = models.CharField(max_length=200)
    creation_date = models.DateTimeField('date created', default=datetime.datetime.now())
    list_user = models.ForeignKey(User)

    def __str__(self):
        return self.list_title

class Item(models.Model):
    item_text = models.CharField(max_length=250)
    creation_date = models.DateTimeField('date created', default=datetime.datetime.now())
    completed = models.BooleanField(default=False)
    todo_list = models.ForeignKey(TodoList)

    def __str__(self):
        return self.item_text

    def save(self, *args, **kw):
        if self.pk is not None:
            orig = Item.objects.get(pk=self.pk)
            if orig.completed != self.completed:
                print ('completed changed')
        super(Item, self).save(*args, **kw)

ToDoApp/todo/forms.py
"""
   Copyright 2016 Andrea McIntosh

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 """

from django.forms import ModelForm, Form, BooleanField
from django.contrib.auth.models import User
from .models import Item, TodoList

class NewItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ['item_text']

class NewListForm(ModelForm):
    class Meta:
        model = TodoList
        fields = ['list_title']

ToDoApp/todo/views.py
"""
   Copyright 2016 Andrea McIntosh

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 """
import datetime
from django.shortcuts import render, render_to_response
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.template import RequestContext
from django.utils import timezone
from django.contrib.auth.forms import UserCreationForm

from .models import TodoList, Item
from .forms import NewItemForm, NewListForm

# Modified from http://www.tangowithdjango.com/book/chapters/login.html, 2016-01-25
def user_login(request):
    context = RequestContext(request)
    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username, password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('todo:viewlists'))
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print ("Invalid login details: {0}, {1}".format(username, password))
            return HttpResponse("Invalid login details supplied.")
    else:
        return render_to_response('todo/login.html', {}, context)

def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('todo:index'))

def register(request):
    context = RequestContext(request)
    if request.method == 'POST':
        user_form = UserCreationForm(data=request.POST)
        if user_form.is_valid():
            # Save the user's form data to the database.
            new_user = user_form.save()
            new_user.set_password(user_form.cleaned_data.get('password1'))
            new_user.save()
            new_user = authenticate(username=user_form.cleaned_data.get('username'), password=user_form.cleaned_data.get('password1'))
            login(request, new_user)
            return HttpResponseRedirect(reverse('todo:viewlists'))
        # Invalid form or forms - mistakes or something else?
        else:
            print (user_form.errors)
    else:
        user_form = UserCreationForm()

    return render_to_response(
            'todo/register.html',
            {'user_form': user_form,},
            context)

@login_required
def new_item(request, pk):
    if request.method == 'POST':
        form = NewItemForm(request.POST or None)
        if form.is_valid():
            newitem = form.save(commit=False)
            newitem.item_text = form.cleaned_data['item_text']
            newitem.creation_date = timezone.now()
            newitem.todo_list = TodoList.objects.get(id=pk)
            newitem.save()
            return HttpResponseRedirect(reverse('todo:detail', kwargs={'pk': pk})) # Redirect after POST
    else:
        form = NewItemForm()

    return render(request, 'todo/newitem.html', {'form': form})

@login_required
def new_list(request):
    if request.method == 'POST':
        form = NewListForm(request.POST)
        if form.is_valid():
            newlist = form.save(commit=False)
            newlist.item_text = form.cleaned_data['list_title']
            newlist.creation_date = timezone.now()
            newlist.list_user = request.user
            newlist.save()
            return HttpResponseRedirect(reverse('todo:viewlists'))
    else:
        form = NewListForm() 

    return render(request, 'todo/newlist.html', {
        'form': form,
    })

def index_view(request):
    template_name = "todo/index.html"
    return render(request, template_name)

def view_lists(request):
    latest_todo_list = TodoList.objects.filter(list_user=request.user)
    context = {'latest_todo_list': latest_todo_list}
    return render(request, 'todo/viewlists.html', context)

def list_details(request, pk):
    thislist = TodoList.objects.filter(id=pk)
    list_items = Item.objects.filter(todo_list=thislist)
    context = {'list_items': list_items, 'thislist': thislist, 'listid': pk}

    done = request.POST.getlist('check')
    for i in done:
        item = list_items.filter(id=i)
        for instance in item:
            instance.completed = True
            instance.save()
    return render(request, 'todo/detail.html', context)

ToDoApp/todo/templates/todo/detail.html
<!--
   Copyright 2016 Andrea McIntosh

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 -->
 {% load staticfiles %}
 <link rel="stylesheet" type="text/css" href="{% static 'todo/style.css' %}" />

{% for alist in thislist %}
    <h1>{{ alist.list_title }}</h1>
{% endfor %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form method="post" action="{% url 'todo:detail' listid  %}" >
    {% if list_items.count %}
        <input type="submit" value="Completed selected items!" class="complete itembutton" />
    {% endif %}
    <ul id="itemlistbox">
        {% for item in list_items %}
            <li>
                <!-- If item is not completed have chackbox to allow user to complete it.
                    If it is completed remove checkbox and strike-through text -->
                {% csrf_token %}
                {% if item.completed %}
                    <strike>
                {% endif %}
                    {{ item.item_text }}
                {% if item.completed %}
                    </strike>
                {% else %}
                    <input type="checkbox" id="check{{ item.id }}" value="{{ item.id }}" name="check" />
                {% endif %}
            </li>
        {% endfor %}
    </ul>
</form>
<a href="{% url 'todo:new_item' listid  %}"><input type="submit" value="Add new item" class="submit itembutton" /></a>

<div class="buttonfooter">
    <a href="{% url 'todo:logout' %}" ><button class="logout">Logout</button></a>
    <a href="{% url 'todo:viewlists' %}" ><button class="viewall">All Lists</button></a>
</div>

ToDoApp/todo/templates/todo/index.html
<!--
   Copyright 2016 Andrea McIntosh

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 -->

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'todo/style.css' %}" />

<h1>Todo App</h1>
<a class="index" href="{% url 'todo:login' %}"><span>Login</span></a>
<a class="index" href="{% url 'todo:register' %}"><span>Register</span></a>

ToDoApp/todo/templates/todo/logged_out.html
Logged out!

ToDoApp/todo/templates/todo/newitem.html
<!--
   Copyright 2016 Andrea McIntosh

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 -->

 {% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'todo/style.css' %}" />

<h1>What to do?</h1>
<form method="post" action="" >
    {% csrf_token %}
    {% for field in form %}
        {# {{ field.errors }} #}
        {{ field }}
    {% endfor %}
    <input type="submit" value="Add" class="create" />
</form>

<div class="buttonfooter">
    <a href="{% url 'todo:logout' %}" ><button class="logout">Logout</button></a>
    <a href="{% url 'todo:viewlists' %}" ><button class="viewall">All Lists</button></a>
</div>

ToDoApp/todo/templates/todo/newlist.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'todo/style.css' %}" />

<form method="post" action="" >
    {% csrf_token %}
    {{ form }}
</form>

ToDoApp/todo/templates/todo/register.html
<!--
   Copyright 2016 Andrea McIntosh

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 -->
<form method="post" action="" >
    {% csrf_token %}
    {{ user_form.as_p }}
    <input type="submit" name="submit" value="Register" />
</form>

ToDoApp/todo/templates/todo/viewlists.html
<!--
Copyright 2016 Andrea McIntosh

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'todo/style.css' %}" />

<h1>Your Todo Lists:</h1>
<div id="listbox">
    {% if latest_todo_list %}
        <ul>
        {% for todolist in latest_todo_list %}
            <li><a href="{% url 'todo:detail' todolist.id %}">{{ todolist.list_title }}</a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No lists are available.</p>
    {% endif %}
    <ul>
        <li style="list-style-type:none">
            <form method="post" action="{% url 'todo:new_list' %}" >
                {% csrf_token %}
                <input type="submit" value="Create New List" class="submit" />
            </form>
        </li>
    </ul>
</div>


<div class="buttonfooter">
    <a href="{% url 'todo:logout' %}" ><button class="logout">Logout</button></a>
</div>